import type { Metadata } from "next";
import "./globals.css";
import GlobalStateManager from "@/Utils/GlobalStateManager";
import Toast from "@/Utils/Toast";

export const metadata: Metadata = {
  title: "register activity",
  description: "Generated by sanjivanipune.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section className="w-screen">{children}</section>;
}
